function setup() {
    var db = color(8, 8, 138);
    var mb = color(46, 100, 254);
    var lb = color(88, 172, 250);
    var bl = 'black';
    var w = 'white';
    var dlx = 0;
    var dtx = 54;
    var dbx = 54;
    var drx = 108;
    var dly = 60;
    var dty = 0;
    var dby = 120;
    var dry = 60;
    var ncx = 108;
    var ncy = 120;
    var hcx = 54;
    var hcy = 60;
    var dia = quad(dlx, dly, dtx, dty, drx, dry, dbx, dby);
    createCanvas (540, 720);
    background (db);
    fill(mb);
    quad(dlx, dly, dtx, dty, drx, dry, dbx, dby);
    dlx += ncx;
    dly += ncy;
    dtx += ncx;
    dty += ncy;
    dbx += ncx;
    dby += ncy;
    drx += ncx;
    dry += ncy;
    quad(dlx, dly, dtx, dty, drx, dry, dbx, dby);
    dlx += ncx;
    dly += ncy;
    dtx += ncx;
    dty += ncy;
    dbx += ncx;
    dby += ncy;
    drx += ncx;
    dry += ncy;
    dia;
}